CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
# Force this side to act as peripheral (central is the default option)
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=n

CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y